### ISSUE TITLE
This is only for Chrome/Chromium or also for Firefox ?

### ISSUE THREAD

**Issue by shirishag75** [gorhill/sessbench#4]
Would love to have such a script for Mozilla Firefox. I know Mozilla's Tools > Developer Tools > Network gives something similar but it would be nice if there was an independent thing as well and if it could use mozjs or whatever it is that makes mozilla run and run over a few websites with the script as you have shared, would be nice. 

https://github.com/gorhill/uBlock/wiki/Reference-benchmark

If you can't (due to lack of time) and if you know of somebody who has done something similar please let me know.

**Comment by gorhill** [comment]
It's on the front page of the project:

> A developer tool to benchmark realistic browser sessions **for Chromium-based browsers** in order to extract privacy-related stats.
